# Use the official .NET 6 SDK image as the parent image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

# Set the working directory in the container
WORKDIR /app

# Copy the solution file
COPY Rutnät.sln .

# Copy each csproj and restore to cache the layers
COPY Presentation/Presentation.csproj Presentation/
COPY Infrastructure/Infrastructure.csproj Infrastructure/
COPY Application/Application.csproj Application/
COPY Domain/Domain.csproj Domain/
RUN dotnet restore

# Copy the rest of the files and build
COPY . ./
RUN dotnet publish Presentation -c Release -o out

# Use the .NET 6 runtime image for the final image
FROM mcr.microsoft.com/dotnet/aspnet:6.0

# Set the working directory in the container
WORKDIR /app

# Copy the published app from the build-env image
COPY --from=build-env /app/Presentation/out .

# Start the app
ENTRYPOINT ["dotnet", "Presentation.dll"]
